### ISSUE TITLE
32 bit incompability

### ISSUE THREAD

**Issue by joeschman** [ZeroCostGoods/sysconf.rs#4]
It's not possible to compile the crate on a 32 bit system (i.e.: my raspberry pi 2). This might be the case due to c types being mapped to different rust types in 32 and 64 bit systems.

```
error[E0308]: mismatched types
  --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/sysconf-0.1.2/src/lib.rs:76:19
   |
76 |         ret => Ok(ret),
   |                   ^^^ expected i64, found i32

error: aborting due to previous error(s)

error: Could not compile `sysconf`.
```

**Comment by gmjosack** [comment]
Hey @joeschman 

Sorry about that. I admittedly don't normally consider 32-bit systems these days :(

I just pushed a new version (`0.2.0`) to crates.io. Please let me know if you continue to see issues.

Thanks for the report!
