### ISSUE TITLE
Missing windows dependencies

### ISSUE THREAD

**Issue by joshlf** [ZeroCostGoods/sysconf.rs#8]
`Cargo.toml` is missing `kernel32` and `winapi` dependencies, which are used on Windows.

@gmjosack , would you be OK with enabling AppVeyor for this repository? If you do that, I can add an `appveyor.yml` so we can catch issues like this in the future - I caught it on the AppVeyor tests of a project that depends on this crate.

**Comment by gmjosack** [comment]
I've enabled appveyor. Feel free to submit a PR for the `appveyor.yaml` or I can get to it sometime tomorrow.
